[project]
name = "dl-cv-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "numpy>=2.2.6",
    "pandas>=2.3.0",
]
